### ISSUE TITLE
[BUG] Error when visualize Movinet

### ISSUE THREAD

**Issue by Mob97** [paulgavrikov/visualkeras#10]
**Describe the bug**
I tried to visualize [MoviNet model](https://github.com/tensorflow/models/tree/master/official/vision/beta/projects/movinet) then I got this error. I guess that because of the casual convolution.
```
Traceback (most recent call last):
  File "visulize_model.py", line 14, in <module>
    visualkeras.layered_view(model, to_file='output.png') # write to disk
  File "/*/*/*/*/*/python3.7/site-packages/visualkeras/layered.py", line 94, in layered_view
    x = min(max(shape[1] * scale_xy, x), max_xy)
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
```

**Minimal Code To Reproduce**
```
visualkeras.layered_view(model, to_file='output.png')
```

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - Python [e.g. Python 3.8]

**Comment by paulgavrikov** [comment]
@Mob97 how did you install visualkeras and which version are you testing?

**Comment by Mob97** [comment]
> @Mob97 how did you install visualkeras and which version are you testing?

I installed by pipy (pip install visualkeras) and I think I'm using visualkeras 0.0.2.

**Comment by paulgavrikov** [comment]
@Mob97 Could you try the latest master and see if the error persists? I recently fixed a bug related to invalid shapes but I am not sure if this is the same issue: `pip install -U git+https://github.com/paulgavrikov/visualkeras`

Also, could you please provide the `model.summary()` log?
