### ISSUE TITLE
[BUG]AttributeError: 'Sequential' object has no attribute '_layers'

### ISSUE THREAD

**Issue by JuggernautPanda** [paulgavrikov/visualkeras#14]
import visualkeras
model.build()
visualkeras.layered_view(model, legend=True, to_file='output.png').show() # write and show
visualkeras.graph_view(model,show_neurons=True, to_file='graph.png').show()

AttributeError                            Traceback (most recent call last)
<ipython-input-10-088be0cee152> in <module>()
      2 model.build()
      3 visualkeras.layered_view(model, legend=True, to_file='output.png').show() # write and show
----> 4 visualkeras.graph_view(model,show_neurons=True, to_file='graph.png').show()

1 frames
/usr/local/lib/python3.7/dist-packages/visualkeras/layer_utils.py in model_to_adj_matrix(model)
     37         if not model.built:
     38             model.build()
---> 39     layers = model._layers
     40 
     41     adj_matrix = np.zeros((len(layers), len(layers)))

AttributeError: 'Sequential' object has no attribute '_layers'

**Comment by JuggernautPanda** [comment]
I tried the fix by changing the _layers to layers.

I get a new issue:

/usr/local/lib/python3.7/dist-packages/visualkeras/layer_utils.py in model_to_adj_matrix(model)
     55             src = id_to_num_mapping[inbound_layer_id]
     56             tgt = id_to_num_mapping[layer_id]
---> 57             adj_matrix[src, tgt] += 1
     58 
     59     return id_to_num_mapping, adj_matrix

IndexError: index 12 is out of bounds for axis 1 with size 12

**Comment by paulgavrikov** [comment]
What tensorflow version are you using? Sounds like an older one. `_layers` contains layers that tensorflow implicitly adds, so I'd assume that when you forgot to change it somewhere.

**Comment by alessiogmonti** [comment]
> What tensorflow version are you using? Sounds like an older one. `_layers` contains layers that tensorflow implicitly adds, so I'd assume that when you forgot to change it somewhere.

Hey- I'm having the same `'Sequential' object has no attribute '_layers' `  issue. I'm using tensorflow 2.7. Any idea what it might be?

**Comment by paulgavrikov** [comment]
@alessiogmonti I will take a look at this, but due to the upcoming CVPR deadline it will take a while. It looks like the `_layers` attribute has been abandoned and seems to have been replaced by `_self_tracked_trackables` in recent tensorflow versions. Could you try changing it? Also, does the bug only affect `graph_view` or also `layered_view`?

**Comment by alessiogmonti** [comment]
@paulgavrikov replacing `_layers` with `_self_tracked_trackables` works great- thank you! It runs just fine now. This bug only affects `graph_view`.

**Comment by paulgavrikov** [comment]
@alessiogmonti awesome. Would you like to try and create a PR that fixes this? You could check if the passed model has the _layers arg and fallback to the other solution if not. Ideally, we’d also integrate a test into Travis CI

**Comment by alessiogmonti** [comment]
@paulgavrikov Absolutely- I'll do this today.

**Comment by jainakhil88** [comment]
> @alessiogmonti awesome. Would you like to try and create a PR that fixes this? You could check if the passed model has the _layers arg and fallback to the other solution if not. Ideally, we’d also integrate a test into Travis CI

Any updates on this, is it fixed? I am getting below error
![image](https://user-images.githubusercontent.com/7304372/143793056-d567d145-264b-44ec-8c8c-e0fd456b12f1.png)

**Comment by alessiogmonti** [comment]
Hey I'll be pushing an update in the next few hours- this completely slipped my mind. For now you can use this:
 `!pip install git+https://github.com/alessiogmonti/visualkeras`

**Comment by paulgavrikov** [comment]
The PR has been merged into the master branch.
@jainakhil88 Your issue is related to something else. It looks like you are not passing a valid Keras model to visualkeras. Are you sure `MaskRCNN` is not wrapping the actual model?
