### ISSUE TITLE
[BUG] TypeError: 'int' object is not iterable`

### ISSUE THREAD

**Issue by sachinprabhu007** [paulgavrikov/visualkeras#15]
Hello

Can someone please assist with this error : int object is not iterable

Model is as follows

model = tf.keras.models.Sequential([
    tf.keras.layers.Embedding(10000, 16, input_length=50),
    tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(20, return_sequences=True)),
    tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(20)),
    tf.keras.layers.Dense(6, activation='softmax')
])

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_41/1631863949.py in <module>
      2 #visualkeras.layered_view(model)
      3 
----> 4 visualkeras.layered_view(model).show() # display using your system viewer
      5 visualkeras.layered_view(model, to_file='output.png') # write to disk

/opt/conda/lib/python3.7/site-packages/visualkeras/layered.py in layered_view(model, to_file, min_z, min_xy, max_z, max_xy, scale_z, scale_xy, type_ignore, index_ignore, color_map, one_dim_orientation, background_fill, draw_volume, padding, spacing, draw_funnel, shade_step, legend, font, font_color)
     98             x = min(max(shape[1] * scale_xy, x), max_xy)
     99             y = min(max(shape[2] * scale_xy, y), max_xy)
--> 100             z = min(max(z), max_z)
    101         elif len(shape) == 2:
    102             if one_dim_orientation == 'x':

TypeError: 'int' object is not iterable`

Thank you!

**Comment by paulgavrikov** [comment]
@sachinprabhu007 Sounds like you are using an older version that had a bug. Try updating directly to the git master: `pip install git+https://github.com/paulgavrikov/visualkeras --upgrade`

**Comment by felipegbazan** [comment]
@paulgavrikov  and @sachinprabhu007  have the exact same problem here. 

Already tried to update directly to the gist master.

**Comment by Modakeo** [comment]
Same issue when using Conv1D layer with tensorflow 2.6

**Comment by paulgavrikov** [comment]
I have could not recreate the issue with the code that OP provided. Neither with TF2.4 nor 2.6. The error logs provided here show outdated code (see https://github.com/paulgavrikov/visualkeras/blob/master/visualkeras/layered.py#L105). Please uninstall visualkeras as reinstall from the github master and see if the issue is still there.

@melioristic Could your provide a your model code?

**Comment by melioristic** [comment]
@paulgavrikov 

I think there is something other than tensorflow here. I am attaching the code with works perfectly on Google Colab, but does not work on my computer locally. I think it has something to do with the python version we are using. 

I am attaching first the output from Colab before the image.

```
----------------
2.6.0
3.7.12 (default, Sep 10 2021, 00:21:48) 
[GCC 7.5.0]
----------------
```

While the output from the local system on which this is not working is. 
```
----------------
2.6.0
3.9.7 (default, Sep 16 2021, 08:50:36) 
[Clang 10.0.0 ]
----------------
2021-10-31 13:34:49.743859: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "/Users/mohitanand/DocL/repo/vis_nn/vis.py", line 37, in <module>
    visualkeras.layered_view(model)
  File "/opt/miniconda3/envs/VIS39/lib/python3.9/site-packages/visualkeras/layered.py", line 100, in layered_view
    z = min(max(z), max_z)
TypeError: 'int' object is not iterable
```

The entire code for this is:
```
import visualkeras
import tensorflow as tf
import sys

print("----------------")
print(tf.__version__)
print(sys.version)
print("----------------")
senn_input = tf.keras.layers.Input(shape=(365,3), name='img')

concept = tf.keras.layers.Flatten()(senn_input)

x = tf.keras.layers.Conv1D(filters=8, kernel_size = 3)(senn_input)
x = tf.keras.layers.MaxPool1D(2)(x)

x = tf.keras.layers.Conv1D(filters=8, kernel_size = 3)(x)
x = tf.keras.layers.MaxPool1D(2)(x)

x = tf.keras.layers.Conv1D(filters=16, kernel_size = 3)(x)
x = tf.keras.layers.MaxPool1D(2)(x)

x = tf.keras.layers.Conv1D(filters=16, kernel_size = 3)(x)
x = tf.keras.layers.MaxPool1D(2)(x)

x = tf.keras.layers.Conv1D(filters=32, kernel_size = 3)(x)
x = tf.keras.layers.MaxPool1D(2)(x)

x = tf.keras.layers.Flatten()(x)
x = tf.keras.layers.Dense(1095)(x)

output = output = tf.math.reduce_sum(tf.math.multiply(x, concept), axis = 1)

model = tf.keras.Model(senn_input, output, name='senn')

visualkeras.layered_view(model)

```

Testing in Python 3.9.7 can be a way to really find out what is not working.

**Comment by paulgavrikov** [comment]
@melioristic But I can definetly see that it is an older version, because that code line is no longer present in the master. I see that you are using miniconda. Are you sure that you have updated with the `--upgrade` param and in the miniconda context?

**Comment by melioristic** [comment]
```
VIS39) mohitanand@pc-15-77 vis_nn % pip install git+https://github.com/paulgavrikov/visualkeras

Collecting git+https://github.com/paulgavrikov/visualkeras
  Cloning https://github.com/paulgavrikov/visualkeras to /private/var/folders/jb/yd5pswy96nv06pk79prrv65c0000gn/T/pip-req-build-4zskvhjm
  Running command git clone -q https://github.com/paulgavrikov/visualkeras /private/var/folders/jb/yd5pswy96nv06pk79prrv65c0000gn/T/pip-req-build-4zskvhjm
  Resolved https://github.com/paulgavrikov/visualkeras to commit ae941a48a0d965b59507690dd7d8f53bc3f66f6f
Requirement already satisfied: pillow>=6.2.0 in /opt/miniconda3/envs/VIS39/lib/python3.9/site-packages (from visualkeras==0.0.2) (8.4.0)
Requirement already satisfied: numpy>=1.18.1 in /opt/miniconda3/envs/VIS39/lib/python3.9/site-packages (from visualkeras==0.0.2) (1.19.5)
Requirement already satisfied: aggdraw>=1.3.11 in /opt/miniconda3/envs/VIS39/lib/python3.9/site-packages (from visualkeras==0.0.2) (1.3.12)
(VIS39) mohitanand@pc-15-77 vis_nn % python vis.py                                              
----------------
2.6.0
3.9.7 (default, Sep 16 2021, 08:50:36) 
[Clang 10.0.0 ]
----------------
2021-10-31 19:02:19.052159: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "/Users/mohitanand/DocL/repo/vis_nn/vis.py", line 35, in <module>
    visualkeras.layered_view(model)
  File "/opt/miniconda3/envs/VIS39/lib/python3.9/site-packages/visualkeras/layered.py", line 100, in layered_view
    z = min(max(z), max_z)
TypeError: 'int' object is not iterable
```

I would say I have.

**Comment by paulgavrikov** [comment]
@melioristic Your log doesn't show that visualkeras was installed. You should see something like this 
```
Successfully built visualkeras
Installing collected packages: visualkeras
  Attempting uninstall: visualkeras
    Found existing installation: visualkeras 0.0.2
    Uninstalling visualkeras-0.0.2:
      Successfully uninstalled visualkeras-0.0.2
Successfully installed visualkeras-0.0.2
```

Could you try: `pip install git+https://github.com/paulgavrikov/visualkeras --upgrade` or `python -m pip install git+https://github.com/paulgavrikov/visualkeras --upgrade` if the first one doesn't help. The upgrade flag should uninstall your local version and checkout and install a fresh one.

**Comment by melioristic** [comment]
@paulgavrikov Thanks. It worked. So the thing is I tried to run the above commands and it did not work. But then I did pip uninstall visualkeras. And then ran your code (``` pip install git+https://github.com/paulgavrikov/visualkeras --upgrade```) and it worked. If you have an idea why that could have been that will be really helpful. And thanks again.

**Comment by paulgavrikov** [comment]
@melioristic I believe pip creates a log somewhere, you could check that but I am not sure why you couldn't just run `--upgrade`. Works fine for me.

**Comment by shahidzk1** [comment]
@paulgavrikov do you have any suggestions?
![Screenshot from 2023-09-22 13-41-19](https://github.com/paulgavrikov/visualkeras/assets/47216877/eefc3e7d-6ac9-4279-96ad-a07b560d8e73)

**Comment by paulgavrikov** [comment]
@shahidzk1 there must be an issue with python using the wrong visualkeras version. I suggest to remove it via pip and then run a clean install from the github main
