### ISSUE TITLE
[REQUEST] Add layer name and tensor shapes

### ISSUE THREAD

**Issue by ekardnam** [paulgavrikov/visualkeras#16]
This is very quick to deploy to Google Colab and I dont have to install everything on my computer which is great, but it would be nice if there was the possibility to have the layer names as well as the tensor shapes plotted (i.e. for convolutional layers height x width @ kernel number).

The only alternative to this is opening the file on photoshop and editing it by hand which isnt very good for productivity i guess.

**Comment by S-Erik** [comment]
I added the tensor shapes as text below the layers in my fork and just created a pull request so that this feature finds its way into the main repository.
