### ISSUE TITLE
[BUG] Color map in Layered_view not changing colors

### ISSUE THREAD

**Issue by alessiogmonti** [paulgavrikov/visualkeras#22]
Specifying a color map as in the readme example does not result in the desired colors being mapped to the network diagram.

```
import tensorflow as tf
IMG_SHAPE = (224, 224, 3)
model0 = tf.keras.applications.EfficientNetB0(input_shape=IMG_SHAPE, include_top=False, weights="imagenet")
tf.keras.utils.plot_model(model0) 
model0.summary() 

import visualkeras
from tensorflow.python.keras.layers import InputLayer,Rescaling,Normalization,ZeroPadding2D,Conv2D,BatchNormalization,Activation,DepthwiseConv2D,GlobalAveragePooling2D,Reshape,Multiply,Dropout,Add
from collections import defaultdict

colorMap = defaultdict(dict)
colorMap[InputLayer]['fill'] = 'red'
colorMap[Rescaling]['fill'] = 'blue'
colorMap[Normalization]['fill'] = 'green'
colorMap[ZeroPadding2D]['fill'] = 'orange'
colorMap[Conv2D]['fill'] = 'pink'
colorMap[BatchNormalization]['fill'] = 'purple'
colorMap[Activation]['fill'] = 'yellow'
colorMap[DepthwiseConv2D]['fill'] = 'grey'
colorMap[GlobalAveragePooling2D]['fill'] = 'black'
colorMap[Reshape]['fill'] = 'brown'
colorMap[Multiply]['fill'] = 'teal'
colorMap[Dropout]['fill'] = 'navy'
colorMap[Add]['fill'] = 'crimson'

visualkeras.layered_view(model0, legend=True, max_xy=900, max_z=0.5, color_map=colorMap)  
```
I am running tensorflow 2.7.0 with Python 3.7.12 in google colab.

**Comment by paulgavrikov** [comment]
That is actually a valid bug. visualkeras will map against the import you have used, unfortunately there are at least 3 ways to import the layers (`tensorflow.keras`, `keras`, `tensorflow.python.keras`). So, we should check them all or find a way to do a better mapping.

**Comment by elliestath** [comment]
Hey, I have a UNet architecture with an EfficientNetb0 backbone using the [segmentation_models](https://segmentation-models.readthedocs.io/en/latest/api.html?highlight=layer#segmentation_models.Unet) library
I manage to access the layers by doing 

> color_map[keras.layers.Conv2D]['fill'] = 'royalblue'

but I cannot access the FixedDropout layer.
Do you have any idea on how I can do this?

**Comment by Andre1989** [comment]
This bug is still valid. Colormap does nothing and also cancels the "type_ignore" argument.
