### ISSUE TITLE
[REQUEST] Skip connections / Residual blocks rendering

### ISSUE THREAD

**Issue by ldeluigi** [paulgavrikov/visualkeras#23]
It would be awesome if some arrows would display _skip connections_ like this:
![image](https://user-images.githubusercontent.com/44567586/146385218-f21efbd4-e457-49ce-8aaa-77ed41255664.png)

**Comment by ldeluigi** [comment]
![image](https://user-images.githubusercontent.com/44567586/146388785-cb8c0d81-000d-4cf9-b50c-487e32f7c2da.png)
Hand made example

**Comment by paulgavrikov** [comment]
Hi @ldeluigi I totally agree that this would be very useful. However, I would rather see this as part of a larger effort to include non-linear models. For example, there could also be downsampling convs on the skip connections, which visualkeras cannot show as of now. Feel free to participate in a PR if you'd like. There's also some starting code in an etra branch https://github.com/paulgavrikov/visualkeras/tree/non_sequential_layered_view
