### ISSUE TITLE
LSTM visualization [BUG]

### ISSUE THREAD

**Issue by MohamedNedal** [paulgavrikov/visualkeras#34]
**Describe the bug**
I have trained a bidirectional LSTM model and I would like to visualize it using this tool. I got the errors in the attached screenshots.

**Screenshots**
![image](https://user-images.githubusercontent.com/43330567/226908301-f31129ee-135e-41e5-988f-6dda18f3e979.png)

![image](https://user-images.githubusercontent.com/43330567/226909048-2bc3d4f6-b114-451b-9e61-c4917cdbe85d.png)

**Environment:**
 - OS: Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-144-generic x86_64) 
 - Jupyter Notebook on Python 3.6.13

**Comment by paulgavrikov** [comment]
Hi,this is a problem with the pypi hosted version, please install visualkeras directly from GitHub (see #8)
