### ISSUE TITLE
[Help Wanted] Legends not working?

### ISSUE THREAD

**Issue by GentianGashi** [paulgavrikov/visualkeras#5]
`visualkeras.layered_view(model, to_file='output.png', legend=True).show()`
TypeError: layered_view() got an unexpected keyword argument 'legend'

Not sure what's going on here, everything seems to work but legends=True persists with that error message, any ideas?

**Comment by paulgavrikov** [comment]
Hi @GentianGashi, 
please use the issue template to create new issues. Anyway, I guess you have installed visualkeras from pypi? Legends are currently only supported on the master branch. Simply install via git: `pip install git+https://github.com/paulgavrikov/visualkeras --upgrade`

**Comment by GentianGashi** [comment]
Ah uninstalling the pypi version and installing the updated github version seems to have fixed it, cheers!
