### ISSUE TITLE
[REQUEST] handling specify layers

### ISSUE THREAD

**Issue by andife** [paulgavrikov/visualkeras#54]
Hi, 

I would appreciate the possibility of addressing individual layers separately. 

- For example, to assign different colors. e.g. also to the different layers [e.g. conv2d, conv2d_1,  conv2d_2, concatenate,...]
- annotate the different boxes with the layer names

**Comment by Soontosh** [comment]
Hi,

I understand what you are asking and I will add this in a future version. I'll be updating the README.md with a roadmap of features and bugfixes which I would like to add, so look out for that. Thanks for the input!
