### ISSUE TITLE
Unexpected 'legend' argument in layered_view() in Google Colab

### ISSUE THREAD

**Issue by jaredible** [paulgavrikov/visualkeras#6]
<img width="1350" alt="issue" src="https://user-images.githubusercontent.com/5361742/111664752-19310880-87e0-11eb-87b1-79cdfaccf825.png">

**Comment by paulgavrikov** [comment]
Hi @jaredible,
the published v0.0.1 does not support legends. I have not released the legend feature on pypi, yet - but you can install the latest github master: `pip install git+https://github.com/paulgavrikov/visualkeras`

**Comment by wayzz1992** [comment]
> Hi @jaredible,
> the published v0.0.1 does not support legends. I have not released the legend feature on pypi, yet - but you can install the latest github master: `pip install git+https://github.com/paulgavrikov/visualkeras`

I have tried installing this version but i'm still getting version 0.0.1 on pip and 'legend' argument still throwing error.

**Comment by paulgavrikov** [comment]
@wayzz1992 have you uninstalled the pypi release prior to installing this? You can also force this via: `pip install git+https://github.com/paulgavrikov/visualkeras --upgrade`

**Comment by wayzz1992** [comment]
> @wayzz1992 have you uninstalled the pypi release prior to installing this? You can also force this via: `pip install git+https://github.com/paulgavrikov/visualkeras --upgrade`

Yes I uninstalled using pip uninstall visualkeras and used the one provided by yourself.

When I run the below code I still get : TypeError: layered_view() got an unexpected keyword argument 'legend'

`visualkeras.layered_view(modelone, to_file='output.png', legend=True)`

**Comment by paulgavrikov** [comment]
@wayzz1992 I still believe that the package is not installed properly. Are you sure you are installing it with the correct python runtime / environment (if you have multiple)? Is this on Google Colab? --> if not please create a new issue and fill out the bug report with as many details as possible. Btw. I have just released the latest code on pypi and it's versioned as 0.0.2, so, perhaps a simple update will help you already.
