### ISSUE TITLE
[Feature Idea] Display layers dimensions on layered_view

### ISSUE THREAD

**Issue by MathisMohand** [paulgavrikov/visualkeras#7]
The layered view works well for me and we can see the changes in size between each layer. However I believe it would be nice to be able to read the dimensions and number of filters / channels of each layer. I haven't dove in the code to create the visualization yet but I believe this is easily obtainable information on keras with `layer.output_shape` for example.

**Comment by S-Erik** [comment]
I added this feature in my fork and made a pull request. Would love to see this added to the main repository.
