### ISSUE TITLE
[BUG] Missing text in legend

### ISSUE THREAD

**Issue by daniel-dona** [paulgavrikov/visualkeras#78]
**Describe the bug**
When legend parameter is set to true some legend is present but without any kind of text.

**Minimal Code To Reproduce**
Check this notebook https://colab.research.google.com/drive/1mDit0vQLI651kpRU_p67XvuGjDxxfy6V?usp=sharing

**Expected behavior**
Show some text in the legend

**Screenshots**
![imagen](https://github.com/user-attachments/assets/4dc70a40-2e3d-4371-a719-aa7c60f12fb1)

![imagen](https://github.com/user-attachments/assets/c3130cb2-8ea5-4484-8dc6-a3bf6f53be68)

**Environment (please complete the following information):**
- Google Colab
- JupyterLab ( quay.io/jupyter/tensorflow-notebook:cuda-latest )

**Additional context**

**Comment by daniel-dona** [comment]
Oops, didn't read that ticket, downgrading to visualkeras==0.1.2 works fine. Thanks!

**Comment by Soontosh** [comment]
No problem, thanks for using visualkeras
