### ISSUE TITLE
[BUG] TypeError if model contains Conv1D layer

### ISSUE THREAD

**Issue by torazem** [paulgavrikov/visualkeras#8]
**Describe the bug**
Running `layered_view()` on a model that contains a `Conv1D` layer results in a TypeError.

**Minimal Code To Reproduce**
```python
from tensorflow import keras
from tensorflow.keras import layers
import visualkeras

x_in = keras.Input(shape=(28, 1))
x = layers.Conv1D(16, 3, activation='relu')(x_in)
x_out = layers.Dense(32)(x)
x_out = layers.Dense(1)(x)
model = keras.Model(x_in, x_out)

visualkeras.layered_view(model, to_file='data/conv1d.png')
```

**Expected behavior**
Image is generated and contains the Conv1D layer.

**Screenshots**
```
Traceback (most recent call last):
  File "experiments/visualkeras_experiments/visualize.py", line 14, in <module>
    visualkeras.layered_view(encoder, to_file='data/conv1d.png')
  File "/path/to/visualkeras/layered.py", line 100, in layered_view
    z = min(max(z), max_z)
TypeError: 'int' object is not iterable
```

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04.5
 - Python 3.8.2
 - Module Version: 0.0.2 (commit 402cec8)

**Comment by paulgavrikov** [comment]
@torazem Thanks for raising this issue. It should be fixed now. Please reinstall visualkeras from the git main branch and let me know if you encounter any problems.

**Comment by torazem** [comment]
It works now, thank you! :sparkles:
